apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-jenkins 
  labels:
    app: application
spec:
  selector:
    matchLabels:
        app: application
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: applicationdemo
          image: 790107037484.dkr.ecr.us-east-1.amazonaws.com/taskprac:version1
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
