apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-jenkins 
  labels:
    app: nodejs-app
spec:
  selector:
    matchLabels:
        app: nodejs-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 790107037484.dkr.ecr.us-east-1.amazonaws.com/taskprac:version1
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
