apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: taskprac
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name:taskprac
        image: 790107037484.dkr.ecr.us-east-1.amazonaws.com/taskprac:version1
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
    k8s-app: nodejsapp
  name: taskprac
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: nodejs
