apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: 790107037484.dkr.ecr.us-east-1.amazonaws.com/taskprac:version1
        env:
        - name: nodejsdemp
          value: production-microservice
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway

spec:
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080
      nodePort: 3000

  type: NodePort
