---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs
      version: blue
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
        version: blue
    spec:
      containers:
      - name: nodejs
        image: 790107037484.dkr.ecr.us-east-1.amazonaws.com/taskprac:version1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
