apiVersion: v1
kind: Service
metadata:
name: kubeapp-ecr-nodeport-service
labels:
   app: kubeapp-ecr
annotations:    
   alb.ingress.kubernetes.io/healthcheck-path: /index.html    
spec:
type: NodePort
selector:
   app: kubeapp-ecr
ports:
   - port: 80
      targetPort: 80
